### ISSUE TITLE
Error with filter() function

### ISSUE THREAD

**Issue by jeesus-bock** [kawamataryo/vue-word-highlighter#773]
I keep getting the following error
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'filter')
    at defaultFindChunks2 (utils.js:96:6)
    at findAll3 (utils.js:30:15)
 ```
query is set correctly to a string, this I've made sure of, but I'm lost of ideas what else could be causing this. Any help is appreciated.

**Comment by jeesus-bock** [comment]
Is it possible that lack of text content in the component, ie. the bulk we want to highlight could be causing this?

**Comment by kawamataryo** [comment]
I see. if you give me a reproduction environment, I'll fix the bug.
